name: sticky_header_list
description: Sticky headers list
version: 1.0.6
author: Josip Krnjic <jokr.dev@gmail.com>
homepage: https://github.com/itsJoKr/sticky_header_list

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


